### ISSUE TITLE
Daemon exits on Enter press

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/yascheduler#5] opened 2019-12-21 22:45 UTC
(may be this is not a bug, but feature?)
Pressing ENTER leads to:
```
"/lib/python3.6/site-packages/invoke/terminals.py", line 231, in bytes_to_read
    fionread = fcntl.ioctl(input_, termios.FIONREAD, "  ")
AttributeError: module 'termios' has no attribute 'FIONREAD'
```

**Comment by ansobolev** [comment] 2019-12-23 08:48
Any definite steps to reproduce?

**Comment by blokhin** [comment] 2019-12-23 09:40
1. Run daemon in foreground
2. Hit Enter

**Comment by ansobolev** [comment] 2019-12-23 09:44
Why do you want to run it in the foreground? It is meant to be run with systemd

**Comment by blokhin** [comment] 2019-12-23 10:16
This is actual for the standalone usage, without AiiDA, e.g. to test some nasty systems

**Comment by ansobolev** [comment] 2019-12-23 10:39
OK, I'll take a look into it

**Comment by ansobolev** [comment] 2020-07-31 18:27
Unfortunately, I cannot reproduce the bug. From the error message it seems like a bug in Python standard lib (`invoke` module). Closing as `WORKSFORME`.

**Closed by ansobolev** 2020-07-31 18:27 UTC
